### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by mzmarshall1278** [Kikimora-Labs/nearpay-sdk#4]
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.

I get this error the moment I import the package. 
same error when I initialized the widget
I'm using next,js

`import { NearPay, SignedWidgetParams } from '@nearpay/nearpay-sdk';
import { useEffect } from 'react';
const Pay = () => {

    const params = {
      toAmount: 10.0,
      toCurrency: 'Near',
      toWallet: 'codeslayer.testnet.near',
      signature: '',
      apiKey: 'a0b89bf1-00c7-4574-9450-0f9812eaf649',
    };

    useEffect(()=> {
      const body = document.querySelector('#body');
         
          const widget = new NearPay({
            mountElement: body,
            environment: 'development',
            params
          });
          
          // Subscribing to events
          widget.addListener('onload', (data) => {
              // react to changes!
              console.log(data);
          });
          
          // render iframe
          widget.init();
    })

    return ( 
        <div id="body"></div>
     );
}
 
export default Pay;

Pay.layout = 'mainLayout'

`

**Comment by klerok96** [comment]
At the moment we don't support SSR (next js).
I can offer to do as it is written here: [link](https://stackoverflow.com/questions/66096260/why-am-i-getting-referenceerror-self-is-not-defined-when-i-import-a-client-side).
My example:
`WidgetInit.js`
```
import { NearPay } from "@nearpay/nearpay-sdk";
import { useEffect } from "react";

const params = {
  toAmount: "",
  toCurrency: "",
  toWallet: "",
  signature: "",
  apiKey: "your-public-api-key",
};

const body = document.querySelector("body");

const widget = new NearPay({
  mountElement: body,
  environment: "development",
  params,
});

export default function WidgetInit() {
  useEffect(() => {
    widget.init();
  }, []);

  return null;
}
```
`index.js`
```
import dynamic from "next/dynamic";

const WidgetInit = dynamic(() => import("./WidgetInit.js"), { ssr: false });

export default function Home() {
  return <WidgetInit />;
}
```
